/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.kelompok2.prak9;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */

public class LihatDataPanel extends javax.swing.JPanel {

    public LihatDataPanel() {
        initComponents();
        loadData(); // PANGGIL loadData() DI SINI
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mahasiswaTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        mahasiswaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(mahasiswaTable);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void loadData() {
    // Nama kolom tabel
    String[] column = {"Nama", "NIM", "Prodi", "Jenis Kelamin", "Status"};
    
    // Buat model tabel (non-editable)
    DefaultTableModel table = new DefaultTableModel(null, column) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Agar tabel tidak bisa diedit
        }
    };
    
    // Isi data dari ArrayList ke tabel
    for (Mahasiswa mhs : Mahasiswa.mahasiswas) {
        table.addRow(new String[]{
            mhs.getNama(),
            mhs.getNim(), 
            mhs.getProdi(),
            mhs.getJenisKelamin(),
            mhs.isActive() ? "Aktif" : "Tidak Aktif"
        });
    }
    
    // Set model ke JTable
    mahasiswaTable.setModel(table);
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mahasiswaTable;
    // End of variables declaration//GEN-END:variables
}
