/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.kelompok2.pbo9;

import javax.swing.JOptionPane;

/**
 *
 * @author desktop
 */
public class TambahDataPanel extends javax.swing.JPanel {

    /**
     * Creates new form TambahDataPanel
     */
    public TambahDataPanel() {
        initComponents();
        lakiRadioBtn.setActionCommand("Laki-laki");
        perempuanRadioBtn.setActionCommand("Perempuan");
    }
    
    public void clearForm() {
        namaTextField.setText("");
        nimTextField.setText("");
        lakiRadioBtn.setSelected(false);
        perempuanRadioBtn.setSelected(false);
        aktifCheckBox.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        tambahDataJPanelLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namaTextField = new javax.swing.JTextField();
        nimTextField = new javax.swing.JTextField();
        prodiComboBox = new javax.swing.JComboBox<>();
        aktifCheckBox = new javax.swing.JCheckBox();
        kirimButton = new javax.swing.JButton();
        lakiRadioBtn = new javax.swing.JRadioButton();
        perempuanRadioBtn = new javax.swing.JRadioButton();

        setLayout(new java.awt.CardLayout());

        tambahDataJPanelLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tambahDataJPanelLabel.setText("Tambah Data Mahasiswa");

        jLabel1.setText("Nama");

        jLabel2.setText("NIM");

        jLabel3.setText("Prodi");

        jLabel4.setText("Jenis Kelamin");

        jLabel5.setText("Status");

        namaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextFieldActionPerformed(evt);
            }
        });

        prodiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S1 Teknik Informatika", "S1 Teknik Elektro", "DE Teknik Elektro" }));

        aktifCheckBox.setText("Aktif");

        kirimButton.setBackground(new java.awt.Color(51, 204, 0));
        kirimButton.setText("Kirim");
        kirimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kirimButtonActionPerformed(evt);
            }
        });

        buttonGroupGender.add(lakiRadioBtn);
        lakiRadioBtn.setText("Laki-laki");

        buttonGroupGender.add(perempuanRadioBtn);
        perempuanRadioBtn.setText("Perempuan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tambahDataJPanelLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaTextField)
                            .addComponent(nimTextField)
                            .addComponent(prodiComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kirimButton)
                                    .addComponent(aktifCheckBox)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lakiRadioBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(perempuanRadioBtn)))
                                .addGap(0, 67, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahDataJPanelLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(prodiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lakiRadioBtn)
                    .addComponent(perempuanRadioBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(aktifCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kirimButton)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void namaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTextFieldActionPerformed

    private void kirimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kirimButtonActionPerformed
        String nama = namaTextField.getText();
        String nim = nimTextField.getText();
        String prodi = (String) prodiComboBox.getSelectedItem();
        String jenisKelamin;
        boolean isActive = aktifCheckBox.isSelected();
        
        if (nama.isEmpty() || nim.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Nama dan NIM wajib diisi!",
                "Error: Input Kosong",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (buttonGroupGender.getSelection() == null) {
            JOptionPane.showMessageDialog(this,
                "Jenis kelamin wajib dipilih!",
                "Error: Pilihan Kosong",
                JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            jenisKelamin = buttonGroupGender.getSelection().getActionCommand();
        }
        
        Mahasiswa mahasiswa = new Mahasiswa(nama, nim, prodi, jenisKelamin, isActive);
        Mahasiswa.mahasiswas.add(mahasiswa);
        
        JOptionPane.showMessageDialog(this, "Sukses menambahkan data mahasiswa " + nama, "Sukses", JOptionPane.INFORMATION_MESSAGE);
        clearForm();
    }//GEN-LAST:event_kirimButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aktifCheckBox;
    private javax.swing.ButtonGroup buttonGroupGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kirimButton;
    private javax.swing.JRadioButton lakiRadioBtn;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JRadioButton perempuanRadioBtn;
    private javax.swing.JComboBox<String> prodiComboBox;
    private javax.swing.JLabel tambahDataJPanelLabel;
    // End of variables declaration//GEN-END:variables
}
